version: '3.8'

services:
  app:
    image: test-straw
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt
    command: ["fastapi", "run", "app/main.py", "--port", "8080"]
